[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[window]
dynamic_padding = true
decorations = "full"
title = "Alacritty@CachyOS"
opacity = 9
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 100
lines = 30

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "0x1E1E1E" # VS Code Dark Modern Background
foreground = "0xD4D4D4" # VS Code Default Text

[colors.normal]
black =   "0x1E1E1E"
red =     "0xF44747"
green =   "0x6A9955"
yellow =  "0xD7BA7D"
blue =    "0x569CD6"
magenta = "0xC586C0"
cyan =    "0x4EC9B0"
white =   "0xD4D4D4"

[colors.bright]
black =   "0x808080"
red =     "0xD16969"
green =   "0xB5CEA8"
yellow =  "0xDCDCAA"
blue =    "0x9CDCFE"
magenta = "0xC586C0"
cyan =    "0x4FC1FF"
white =   "0xFFFFFF"

# Optional: Add selection colors for a true VS Code feel
[colors.selection]
text = "CellForeground"
background = "0x264F78"

[font]
size = 13

[font.normal]
family = "Jetbrains Mono Nerd Font"
style = "Regular"

[font.bold]
family = "Jetbrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "Jetbrains Mono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Jetbrains Mono Nerd Font"
style = "Bold Italic"

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = "Underline"
vi_mode_style = "None"
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[keyboard]
[[keyboard.bindings]]
key = "Paste"
action = "Paste"

[[keyboard.bindings]]
key = "Copy"
action = "Copy"

[[keyboard.bindings]]
key = "L"
mods = "Control"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "L"
mods = "Control"
mode = "~Vi"
chars = "\f"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
mode = "~Alt"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
mode = "~Alt"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "SearchForward"

[[keyboard.bindings]]
key = "B"
mods = "Control|Shift"
action = "SearchBackward"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
mode = "Vi"
action = "ClearSelection"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[general]
live_config_reload = true
working_directory = "None"
